apiVersion: v1
kind: Service
metadata:
  name: epof-backend-delivery-processor-service
  labels:
    app: epof-backend-delivery-processor
spec:
  clusterIP: None
  selector:
    app: epof-backend-delivery-processor
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: epof-backend-delivery-processor
spec:
  serviceName: epof-backend-delivery-processor
  selector:
      matchLabels:
        app: epof-backend-delivery-processor
  replicas: 2
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: epof-backend-delivery-processor
    spec:
      restartPolicy: Always
      containers:
        - name: epof-backend-delivery-processor
          image: epof-backend-delivery-processor:1.0.0-SNAPSHOT
          imagePullPolicy: IfNotPresent
          env:
            - name: SYSTEM_ENV
              value: "int1"
            - name: SYSTEM_INSTANCE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - containerPort: 8080
          startupProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            periodSeconds: 10
            failureThreshold: 100
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
---
kind: Service
apiVersion: v1
metadata:
  name: epof-backend-delivery-processor
spec:
  type: NodePort
  selector:
    app: epof-backend-delivery-processor
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000