server:
  port: 8080
  http2:
    enabled: false

logging:
  level:
    root: WARN
    ch.post: DEBUG
    org.apache.kafka: WARN

management:
  endpoint.health:
    show-details: always
    show-components: always
    probes.enabled: true
  security.enabled: false
  endpoints.web.exposure.include: '*'
  metrics:
    enable:
      jvm: false

epof:
  backend:
    delivery-processor:
      client-id: epof-backend-dev.DeliveryProcessor

spring:
  application:
    name: epof-backend-dev.DeliveryProcessor
